args<-commandArgs(trailingOnly=FALSE)
script<-sub("^--file=","",args[grepl("^--file=",args)][1L])
app_dir<-normalizePath(file.path(dirname(script),".."),mustWork=TRUE)
source(file.path(app_dir,"R/model.R"));source(file.path(app_dir,"R/provenance.R"))
assert<-function(x,label) { if(!isTRUE(x)) stop(paste("FAIL:",label));cat("PASS:",label,"\n") }
fails<-function(expr) inherits(tryCatch(force(expr),error=function(e)e),"error")
d<-read.csv(file.path(app_dir,"data/gss_year.csv"),check.names=FALSE,na.strings=c("","NA"))
s<-read.csv(file.path(app_dir,"data/gss_year_cell_source.csv"),check.names=FALSE)
items<-setdiff(names(s),"year");focals<-c("Happy","Trust","Fair")
primary<-fit_landscape(d,items,"MobilityLag",own_lag=TRUE)
a<-audit_input_provenance(d,s,items,"MobilityLag",own_lag=TRUE,primary=primary)
fi<-match(focals,items)
assert(all(a$summary$primary_n==46L),"primary46 calendar rows retained")
assert(identical(a$summary$restricted_n[fi],c(31L,27L,27L)),"current-Y extract restriction gives31/27/27")
assert(identical(a$summary$restricted_own_lag_carried_n[fi],c(15L,18L,18L)),"inherited own-lag counts remain15/18/18")
assert(abs(a$restricted_landscape$p_bonferroni_universe[fi[1]]-.14019680259)<1e-9,"HAPPY source-restricted Bonferroni44 .1401968")
assert(max(abs(a$current_landscape$b-primary$b))==0,"provided primary landscape unchanged")
b<-do.call(rbind,lapply(items,function(item) {
  keep<-s[[item]]=="extract" & is.finite(d[[item]]) & is.finite(d$MobilityLag) & is.finite(d[[paste0(item,"Lag")]])
  tmp<-data.frame(y=d[[item]][keep],x=d$MobilityLag[keep],lag=d[[paste0(item,"Lag")]][keep])
  fit<-lm(y~x+lag,data=tmp);z<-summary(fit)$coefficients[2,];ci<-confint(fit)[2,]
  data.frame(n=nrow(tmp),b=z[1],se=z[2],ci_lo=ci[1],ci_hi=ci[2],t=z[3],p=z[4])
}))
fields<-c("n","b","se","ci_lo","ci_hi","t","p")
assert(max(abs(as.matrix(b[fields])-as.matrix(a$restricted_landscape[fields])))<1e-9,"all44 restriction results agree with independent stats::lm fits")
assert(all(a$current_landscape$bonferroni_universe_k==44L) && all(a$restricted_landscape$bonferroni_universe_k==44L),"declared family44 unchanged by source restriction")
reordered<-audit_input_provenance(d,s[nrow(s):1L,],items,"MobilityLag",own_lag=TRUE)
assert(identical(a$summary,reordered$summary),"source years align by key, not row position")
dupe<-rbind(s,s[1,]);assert(fails(audit_input_provenance(d,dupe,items,"MobilityLag",own_lag=TRUE)),"duplicate source years rejected")
assert(fails(audit_input_provenance(d,s[-1,],items,"MobilityLag",own_lag=TRUE)),"missing source-year alignment rejected")
bad<-s;bad$Happy[2]<-"unknown";assert(fails(audit_input_provenance(d,bad,items,"MobilityLag",own_lag=TRUE)),"unknown source labels rejected")
stale<-primary;stale$b[1]<-stale$b[1]+1
assert(fails(audit_input_provenance(d,s,items,"MobilityLag",own_lag=TRUE,primary=stale)),"stale primary result cannot acquire new provenance labels")
nolag<-audit_input_provenance(d,s,items,"year",own_lag=FALSE)
assert(all(nolag$summary$primary_n==47L) && identical(nolag$summary$restricted_n[fi],c(32L,28L,28L)),"different predictor/no-own-lag model uses actual47rows and32/28/28 source counts")
assert(all(is.na(nolag$summary$restricted_own_lag_carried_n)),"no-own-lag has inapplicable, not zero, lag counts")
other<-audit_input_provenance(d,s,items,"MobilityLag",covariates="year",own_lag=TRUE,se_method="HC3")
direct<-fit_landscape(d[s$Happy=="extract" & is.finite(d$MobilityLag) & is.finite(d$HappyLag),],"Happy","MobilityLag",covariates="year",own_lag=TRUE,se_method="HC3",missing="per_outcome")
assert(abs(other$restricted_landscape$se[fi[1]]-direct$se)<1e-12,"different model and HC3 are inherited exactly, not silently replaced")
missing_d<-d;missing_d$Health[missing_d$year==2000]<-NA_real_
common<-audit_input_provenance(missing_d,s,items,"MobilityLag",own_lag=TRUE)
per<-audit_input_provenance(missing_d,s,items,"MobilityLag",own_lag=TRUE,missing="per_outcome")
assert(all(common$summary$primary_n==45L) && common$summary$restricted_n[fi[1]]==30L,"finite common-row mask carries into each restricted model")
assert(per$summary$primary_n[fi[1]]==46L && per$summary$restricted_n[fi[1]]==31L,"per-outcome missingness preserves unaffected outcome rows")
wronglag<-d;wronglag$HappyLag[3]<-wronglag$HappyLag[3]+.1
assert(fails(audit_input_provenance(wronglag,s,items,"MobilityLag",own_lag=TRUE)),"non-calendar own-lag cannot be assigned calendar source labels")
limited<-audit_input_provenance(d,s,focals,"MobilityLag",own_lag=TRUE)
assert(all(limited$restricted_landscape$bonferroni_universe_k==3L) && abs(limited$restricted_landscape$p_bonferroni_universe[1]-limited$restricted_landscape$p[1]*3)<1e-12,"requested-family size, not hardcoded44, controls optional adjustment")
thin<-s;thin$Happy<-"carried";thin$Happy[thin$year==1973]<-"extract"
thin_result<-audit_input_provenance(d,thin,items,"MobilityLag",own_lag=TRUE)
assert(thin_result$restricted_landscape$status[fi[1]]!="ok" && is.na(thin_result$restricted_landscape$p[fi[1]]) && all(thin_result$restricted_landscape$bonferroni_universe_k==44L),"insufficient source-restricted fit stays a failure row and does not shrink family")
repro<-reproduce_input_provenance(file.path(app_dir,"data/gss_year.csv"),file.path(app_dir,"data/gss_year_cell_source.csv"),a$settings)
assert(identical(repro$summary,a$summary) && isTRUE(all.equal(repro$restricted_landscape,a$restricted_landscape)),"simple file/settings reproduction returns identical audit")
assert(any(grepl("not effective sample size",a$method_note,fixed=TRUE)) && any(grepl("not an interpolation",a$method_note,fixed=TRUE)),"interpretation notes distinguish row counts and sample restriction from uncertainty correction")
cat("ALL INPUT-PROVENANCE TESTS PASSED\n")
