source("R/runtime.R")
if (dir.exists(".library")) .libPaths(c(normalizePath(".library"),.libPaths()))
stopifnot(nrow(runtime_mismatches(getwd()))==0L)
locked <- jsonlite::read_json("renv.lock")
stopifnot(!any(c("qs","tidyverse") %in% names(locked$Packages)))
for (p in names(locked$Packages)) stopifnot(packageVersion(p)==package_version(locked$Packages[[p]]$Version))
stopifnot(!file.exists("precomputed_results.rds"))
fixture <- tempfile("runtime-test-"); dir.create(fixture)
write.csv(data.frame(package=c("jsonlite","ampps_package_that_does_not_exist"),version=c("0.0.0","1.0.0")),
  file.path(fixture,"package_versions.csv"),row.names=FALSE)
bad <- runtime_mismatches(fixture)
stopifnot(nrow(bad)==2L,bad$installed[2]=="missing")
unlink(fixture,recursive=TRUE)
cat("PASS: all",length(locked$Packages),"locked package versions match; no qs/tidyverse/precomputed RDS; missing and mismatched dependencies detected.\n")
