args <- commandArgs(trailingOnly=FALSE)
script <- sub("^--file=", "", args[grepl("^--file=", args)][1L])
app_dir <- normalizePath(file.path(dirname(script),".."),mustWork=TRUE)
source(file.path(app_dir,"R/model.R"))
source(file.path(app_dir,"R/export.R"))
assert <- function(value,label) { if (!isTRUE(value)) stop(paste("FAIL:",label)); cat("PASS:",label,"\n") }
fails <- function(expr) inherits(tryCatch(force(expr),error=function(e)e),"error")
sx <- spreadsheet_safe_frame(data.frame(text=c("=formula","\t+formula","normal"),number=c(-1,0,1)))
assert(identical(sx$text,c("'=formula","'\t+formula","normal")) && identical(sx$number,c(-1,0,1)),"spreadsheet-safe text includes whitespace prefixes; numeric cells unchanged")

d <- load_demo_data(file.path(app_dir,"data")); items <- d$metadata$item
assert(length(items)==44L && nrow(d$data)==47L,"demo dimensions")
ledger <- audit_universe(d$data,items,"MobilityLag",own_lag=TRUE)
assert(all(ledger$included) && all(ledger$n_usable==46L),"44 eligible demo outcomes; 46 usable rows")
land <- fit_landscape(d$data,items,"MobilityLag",own_lag=TRUE)
ref <- read.csv(file.path(app_dir,"data/landscape_reference.csv"))
ref <- ref[match(land$item,ref$measure),]
assert(all(land$status=="ok") && all(land$n==46L) && all(land$df==43L),"44 OLS fits, fixed N and df")
fields <- c("b","se","ci_lo","ci_hi","t","p")
err <- max(abs(as.matrix(land[fields])-as.matrix(ref[fields])))
assert(err<1e-8,paste("all 44 estimates/SE/CI/t/p match saved reference; max diff",format(err,digits=3)))
per <- fit_landscape(d$data,items,"MobilityLag",own_lag=TRUE,missing="per_outcome")
assert(isTRUE(all.equal(land[fields],per[fields],tolerance=1e-10)),"demo common/per-outcome same rows and fits")

set.seed(17)
u <- data.frame(x=rnorm(100),z=rnorm(100),a=rnorm(100),b=rnorm(100),c=rnorm(100))
u$a <- .5*u$x+.2*u$z+u$a
f <- fit_landscape(u,c("a","b"),"x",covariates="z")
base <- summary(lm(a~x+z,u))$coefficients[2,]
assert(max(abs(unlist(f[1,c("b","se","t","p")])-base))<1e-12,"OLS agrees with stats::lm")
u$b[1:20] <- NA
common <- fit_landscape(u,c("a","b"),"x",covariates="z")
specific <- fit_landscape(u,c("a","b"),"x",covariates="z",missing="per_outcome")
assert(all(common$n==80L) && identical(specific$n,c(100L,80L)),"common rows versus per-outcome missingness")
hc <- fit_landscape(u,"a","x",covariates="z",se_method="HC3")
lf <- lm(a~x+z,u); mm<-model.matrix(lf); inv<-solve(crossprod(mm))
vr<-inv%*%crossprod(mm,mm*as.numeric((resid(lf)/(1-hatvalues(lf)))^2))%*%inv
assert(abs(hc$se-sqrt(vr[2,2]))<1e-12 && hc$status=="ok","HC3 matches independent lm leverage calculation")
u$constant <- 1; u$text <- "not numeric"
bad <- audit_universe(u,c("a","b","constant","text"),"x",max_missing=.1)
assert(identical(bad$included,c(TRUE,FALSE,FALSE,FALSE)),"ledger flags missingness, constant and nonnumeric outcomes")
failed <- fit_landscape(u,c("a","constant"),"x")
assert(nrow(failed)==2L && failed$status[2] != "ok","failed model remains a row")
assert(fails(fit_landscape(u,"x","x")),"role overlap rejected")
dupe <- u; names(dupe)[2] <- "x"
assert(fails(fit_landscape(dupe,"a","x")),"duplicate headers rejected")
assert(fails(fit_landscape(u,"a","x",covariates="missing")),"missing shared column rejected")
lag_bad <- fit_landscape(u,c("a","b"),"x",own_lag=TRUE)
assert(all(lag_bad$status=="Own-lag column is missing"),"missing own-lag failures retained")
safe <- u; names(safe)[names(safe)=="a"] <- "=system('touch /tmp/NEVER_EXECUTE')"
sf <- fit_landscape(safe,"=system('touch /tmp/NEVER_EXECUTE')","x",covariates="z")
assert(abs(sf$b-f$b[1])<1e-12,"untrusted headers used only as literal column names")

neighborhood <- c("Happy","Trust","Fair","Health","Life","Hapmar","Satjob","Helpful","News","Finrela","Finalter")
r <- make_report_tables(land,c("Happy","Trust","Fair"),neighborhood,d$metadata,TRUE)
assert(nrow(r$focal)==3L && nrow(r$alternatives)==8L,"all three focals and unreported local alternatives retained")
assert(all(r$focal$observed_abs_t_rank_neighborhood==c(1,6,9)),"local observed |t| ranks 1/6/9")
assert(max(abs(r$all$p_bonferroni_universe-ref$p_bonf_44))<1e-9,"Bonferroni all44 matches saved reference")
fr <- make_report_tables(failed,"a",c("a","constant"),multiplicity=TRUE)
assert(all(fr$all$bonferroni_universe_k==2L),"failed fits cannot shrink multiplicity family")
rr <- make_report_tables(land,c("Happy","Trust","Fair"),neighborhood,orientation=c(Happy=-1,Trust=-1,Fair=1))
assert(all(rr$focal$oriented_b>0),"explicit orientation key changes displayed direction, not fitting")

if (file.exists(file.path(app_dir,"R/ega.R"))) {
  work <- tempfile("ampps_export_test_"); dir.create(work)
  archive <- file.path(work,"download_without_extension")
  settings <- c(attr(land,"model_settings"),list(measures=items))
  payload <- list(landscape=land,eligibility=ledger,metadata=d$metadata,settings=settings,report=r,reporting_text="Numerical integration test")
  old_zipcmd<-Sys.getenv("R_ZIPCMD",unset=NA_character_)
  Sys.setenv(R_ZIPCMD="/nonexistent/ampps_test_no_system_zip")
  export_bundle(archive,payload)
  if (is.na(old_zipcmd)) Sys.unsetenv("R_ZIPCMD") else Sys.setenv(R_ZIPCMD=old_zipcmd)
  contents <- unzip(archive,list=TRUE)$Name
  assert(!any(grepl("^inputs/",contents)),"raw input absent from default export")
  assert(all(c("reproduce.R","R/model.R","R/ega.R","settings.json","landscape.csv","report_focal.csv") %in% contents),"reproducibility bundle core files present")
  assert(!any(startsWith(contents,"/")) && !any(grepl("(^|/)\\.\\.(/|$)",contents)),"R-native ZIP preserves relative archive topology without a system zip command")
  included <- file.path(work,"included.zip")
  export_bundle(included,payload,setNames(file.path(app_dir,"data/gss_year.csv"),"analysis_input.csv"))
  extract <- file.path(work,"extract"); dir.create(extract); unzip(included,exdir=extract)
  old<-getwd();setwd(extract)
  result<-system2(file.path(R.home("bin"),"Rscript"),"reproduce.R",stdout=TRUE,stderr=TRUE)
  setwd(old)
  if (!is.null(attr(result,"status"))) cat(paste(result,collapse="\n"),"\n")
  assert(is.null(attr(result,"status")) && file.exists(file.path(extract,"landscape_reproduced.csv")),"downloaded bundle reproduction script executes")
  copied <- read.csv(file.path(extract,"landscape_reproduced.csv"))
  assert(max(abs(as.matrix(copied[fields])-as.matrix(land[fields])))<1e-10,"bundle reproduces all44 numerical outputs")
  assert(unname(tools::md5sum(file.path(extract,"inputs/analysis_input.csv")))==unname(tools::md5sum(file.path(app_dir,"data/gss_year.csv"))),"opt-in input copied byte-for-byte")
  source(file.path(app_dir,"R/ega.R"))
  net <- load_demo_network(file.path(app_dir,"data"))
  full <- payload
  full$settings <- list(app_version="test",source="GSS worked example",run=list(source="demo"),model=attr(land,"model_settings"),focal=c("Happy","Trust","Fair"),boundary="community",network_input_separate=TRUE)
  full$network <- net
  full$neighborhoods <- compare_neighborhoods(net,c("Happy","Trust","Fair"))
  full$annotations <- data.frame(focal="Happy",item="Health",relation="Related outcome",reason="Different domain; do not certify as equivalent")
  full$reporting_text <- c("# AMPPS comparison","<script>alert('escaped')</script>")
  exact <- file.path(work,"root_structure.zip")
  export_bundle(exact,full,setNames(file.path(app_dir,"data/gss_year.csv"),"analysis_input.csv"))
  ext2<-file.path(work,"root_structure");dir.create(ext2);unzip(exact,exdir=ext2)
  assert(all(c("comparison_annotations.csv","network_original_weights.csv","report.html","reproduce_network.R") %in% list.files(ext2)),"root payload annotations, readable HTML, original graph and network script exported")
  st<-jsonlite::read_json(file.path(ext2,"settings.json"),simplifyVector=TRUE)
  assert(identical(st$network$source,"bundled_demo") && !is.null(st$network_record$edge_source) && !is.null(st$network_record$membership_source),"exact graph settings and provenance exported")
  html<-paste(readLines(file.path(ext2,"report.html")),collapse="\n")
  assert(grepl("&lt;script&gt;",html,fixed=TRUE) && !grepl("<script>",html,fixed=TRUE),"HTML report escapes user text")
  assert(grepl("Unreported estimates in the current comparison",html,fixed=TRUE) && grepl("p_bonferroni_universe",html,fixed=TRUE),"HTML includes alternatives and requested multiplicity values")
  assert(file.exists(file.path(ext2,"provenance/gss_year_cell_source.csv")),"GSS cell-source provenance included with frozen network")
  setwd(ext2);nested<-system2(file.path(R.home("bin"),"Rscript"),"reproduce.R",stdout=TRUE,stderr=TRUE)
  frozen<-system2(file.path(R.home("bin"),"Rscript"),"reproduce_network.R",stdout=TRUE,stderr=TRUE);setwd(old)
  assert(is.null(attr(nested,"status")) && is.null(attr(frozen,"status")),"root nested settings reproduce model; demo network explicitly frozen")
  set.seed(710)
  latent<-matrix(rnorm(160*2),160,2)
  nd<-as.data.frame(sapply(1:8,function(j) .8*latent[,if (j<=4) 1 else 2]+.6*rnorm(160)))
  names(nd)<-paste0("Y",1:8);nd$X<-rnorm(160)
  names(nd)[1:2]<-c("=Y1","'=Y1")
  nitems<-names(nd)[1:8]
  npath<-file.path(work,"network.csv");write.csv(nd,npath,row.names=FALSE)
  nd<-read.csv(npath,check.names=FALSE)
  nl<-fit_landscape(nd,nitems,"X")
  nn<-compute_ega(nd,nitems,seed=710)
  np<-list(landscape=nl,settings=list(model=attr(nl,"model_settings"),focal=nitems[1],network_input_separate=FALSE),network=nn,reporting_text="Live EGA roundtrip")
  nzip<-file.path(work,"live.zip");export_bundle(nzip,np,setNames(npath,"analysis_input.csv"))
  ne<-file.path(work,"live");dir.create(ne);unzip(nzip,exdir=ne);setwd(ne)
  nr<-system2(file.path(R.home("bin"),"Rscript"),"reproduce_network.R",stdout=TRUE,stderr=TRUE);setwd(old)
  if (!is.null(attr(nr,"status"))) cat(paste(nr,collapse="\n"),"\n")
  assert(is.null(attr(nr,"status")) && file.exists(file.path(ne,"network_reproduced.rds")),"computed network export reruns actual EGAnet with recorded options")
  nrep<-readRDS(file.path(ne,"network_reproduced.rds"))
  assert(identical(nn$adjacency,nrep$adjacency) && identical(nn$membership,nrep$membership),"live exported network adjacency and membership reproduce exactly")
  setwd(ne);literal<-system2(file.path(R.home("bin"),"Rscript"),"reproduce.R",stdout=TRUE,stderr=TRUE);setwd(old)
  assert(is.null(attr(literal,"status")),"literal formula-like and apostrophe-prefixed identifiers reproduce without collisions")
  unlink(work,recursive=TRUE)
}
cat("ALL MODEL/EXPORT TESTS PASSED\n")
